### PR TITLE
Updated contributors.md file with the branch split-up information

### LINKED ISSUE #79: Update CONTRIBUTING.md
the default branch has changed from `master` to `main`

also added a `dev` branch, all development-related PR should be targeted to the `dev` branch.

documentations or `.github` related PR can optionally merge to the `main` branch directly

### Reference:
- [React Router Contributing Guide](https://github.com/remix-run/react-router/blob/main/docs/guides/contributing.md) is a good example to follow

### PR DESCRIPTION
**Pull request by aswin2108**
## Related Issue(s)
Fixes #79 

## Describe Your Changes
Added details about `dev` branch and `main` branch. Also changed the directions of making a pull request.

### CODE REVIEW

**Comment by aswin2108** [comment]
@kachun333 Any changes needed?

**Comment by kachun333** [comment]
thanks! @aswin2108

**Comment by aswin2108** [comment]
@kachun333 Let me know if there are any other things! code/documentation, I handle both 😁

**Comment by kachun333** [comment]
@aswin2108 , you may pick up these issues if you are interested

https://github.com/kachun333/KMPk-1617-Grad-Mag/issues/78
https://github.com/kachun333/KMPk-1617-Grad-Mag/issues/83
https://github.com/kachun333/KMPk-1617-Grad-Mag/issues/33

**Pull request merged**
